weights: ''
cfg: ./models/yolov5l.yaml
data: ../images/data.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 100
batch_size: 32
imgsz: 416
rect: false
resume: false
nosave: true
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: runs/train
name: xavier_build_yolov5l
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/xavier_build_yolov5l
